spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-service
          uri: lb://DVDTHEQUE-SERVICE
          predicates:
            - Path=/dvdtheque-service/**
        - id: dvdtheque-allocine-service
          uri: lb://DVDTHEQUE-ALLOCINE-SERVICE
          predicates:
            - Path=/dvdtheque-allocine-service/**
        - id: dvdtheque-tmdb-service
          uri: lb://DVDTHEQUE-TMDB-SERVICE
          predicates:
            - Path=/dvdtheque-tmdb-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
    
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    