server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.103:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: "*"
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT