spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: dvdtheque-service
          uri: lb://dvdtheque-service
          predicates:
            - Path=/dvdtheque-service/**
        - id: dvdtheque-allocine-service
          uri: lb://dvdtheque-allocine-service
          predicates:
            - Path=/dvdtheque-allocine-service/**
        - id: dvdtheque-tmdb-service
          uri: lb://dvdtheque-tmdb-service
          predicates:
            - Path=/dvdtheque-tmdb-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/auth/realms/dvdtheque
            # Individual properties can also be provided this way
#            token-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/token
#            authorization-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/auth
#            userinfo-uri: http://localhost:8080/auth/realms/amrutrealm/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: dvdtheque-api
            client-secret: 25d3fa6d-26d2-4c57-807d-7029549fc688
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
    
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    org:
        springframework:
          security:
            web: DEBUG
    