spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - TokenRelay=
        - SaveSession
      routes:
        - id: dvdtheque-service
          uri: lb://dvdtheque-service
          predicates:
            - Path=/dvdtheque-service/**
        - id: dvdtheque-allocine-service
          uri: lb://dvdtheque-allocine-service
          predicates:
            - Path=/dvdtheque-allocine-service/**
        - id: dvdtheque-tmdb-service
          uri: lb://dvdtheque-tmdb-service
          predicates:
            - Path=/dvdtheque-tmdb-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3600
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/dvdtheque-realm
            # Individual properties can also be provided this way
            token-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak: 
            client-id: gateway-client
            client-secret: 86efef59-d234-4a72-9de0-24ee2461effd
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keykloak"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    preferIpAddress: true
    
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    org:
        springframework:
          security:
            web: TRACE
    