spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: lb://DVDTHEQUE-REST-SERVICES
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}