server:
  port: 8762
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: gateway
            client-secret: gateway
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: read
        provider:
          uaa:
            authorization-uri: http://localhost:9999/uaa/oauth/authorize
            token-uri: http://localhost:9999/uaa/oauth/token
            user-info-uri: http://localhost:9999/uaa/api/auth
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9999/uaa/token_keys
      resourceserver:
        jwt:
        jwk-set-uri: http://localhost:9999/oauth/token_keys
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: dvdtheque-rest-services
          uri: lb://DVDTHEQUE-REST-SERVICES
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT