spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-service
          uri: lb://dvdtheque-service
          predicates:
            - Path=/dvdtheque-service/**,/dvdtheque-ws/**
        - id: dvdtheque-allocine-service
          uri: lb://dvdtheque-allocine-service
          predicates:
            - Path=/dvdtheque-allocine-service/**
        - id: dvdtheque-tmdb-service
          uri: lb://dvdtheque-tmdb-service
          predicates:
            - Path=/dvdtheque-tmdb-service/**
        - id: dvdtheque-batch-service
          uri: lb://dvdtheque-batch-service
          predicates:
            - Path=/dvdtheque-batch-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.105:8761/eureka,http://192.168.1.103:8761/eureka
      
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    org.springframework.web.reactive: INFO
    reactor.ipc.netty: INFO
    reactor.netty: INFO