eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.108:8761/eureka},${EUREKA_URI:http://192.168.1.106:8761/eureka}
  instance:
    hostname: 192.168.1.106
    preferIpAddress: true
spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: lb://DVDTHEQUE-REST-SERVICES
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT