server:
  port: 8762
eureka:
  environment: dev
  instance:
    hostname: 192.168.1.105
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.103:8761/eureka,http://192.168.1.105:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-rest-services
          uri: lb://DVDTHEQUE-REST-SERVICES
          predicates:
            - Path=/dvdtheque/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT