spring:
  cloud:
    gateway:
      routes:
        - id: dvdtheque-service
          uri: lb://dvdtheque-service
          predicates:
            - Path=/dvdtheque-service/**
        - id: dvdtheque-allocine-service
          uri: lb://dvdtheque-allocine-service
          predicates:
            - Path=/dvdtheque-allocine-service/**
        - id: dvdtheque-tmdb-service
          uri: lb://dvdtheque-tmdb-service
          predicates:
            - Path=/dvdtheque-tmdb-service/**
        - id: dvdtheque-batch-service
          uri: lb://dvdtheque-batch-service
          predicates:
            - Path=/dvdtheque-batch-service/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - OPTIONS
            - PUT

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.1.108:8761/eureka},${EUREKA_URI:http://192.168.1.106:8761/eureka}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG