jwtSecret: dvd
jwtExpirationMs: 86400000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    url: jdbc:mysql://localhost/dvdtheque?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    type: com.zaxxer.hikari.HikariDataSource
    username: fredo
    password: fredo
    driver-class-name: com.mysql.jdbc.Driver