jwtSecret: dvd
jwtExpirationMs: 86400000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://admin:admin@localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    url: jdbc:mysql://192.168.1.104/dvdtheque?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris&useSSL=false
    username: fredo
    password: fredo
    driver-class-name: com.mysql.jdbc.Driver