jwtSecret: dvd
jwtExpirationMs: 86400000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    url: jdbc:mysql://localhost/dvdtheque?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    type: com.zaxxer.hikari.HikariDataSource
    username: fredo
    password: fredo
    driver-class-name: com.mysql.jdbc.Driver
  security:
    #oauth2:  
      #resourceserver:  
        #jwt: issuer-uri: https://idsvr.example.com/oauth/v2/oauth-anonymous
    filter:
      order: 10
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG