server:
  port: 8761
spring:
  profiles: local
eureka:
  environment: local
  instance:
    hostname: discovery-server-1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/