server:
  port: 8083

spring:
  datasource:
    username: postgres
    password: zotla7
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dvdthequedb?currentSchema=dvdtheque-service
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
  batch:
    job:
      enabled: false
  activemq:
    broker-url: tcp://192.168.1.105:61616
    user: admin
    password: admin
  zipkin:
    enabled: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    org:
        springframework:
          security:
            web: DEBUG
hibernate:
  hbm2ddl:
    auto: validate

batch:
  save:
    nb:
      acteurs: 18
limit:
  film:
    size: 40

tmdb-service:
  url: http://localhost:8762/dvdtheque-tmdb-service
  byTitle: /retrieveTmdbFilmListByTitle/byTitle
  release-date: /retrieveTmdbFrReleaseDate/byTmdbId
  get-credits: /retrieveTmdbCredits/byTmdbId
  get-results: /retrieveTmdbFilm/byTmdbId

dvdtheque-batch-service:
  url: http://localhost:8762/dvdtheque-batch-service
  import: /invokejob/importFilmsJob

themoviedb:
  poster:
    path:
      url: http://image.tmdb.org/t/p/w500

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

stomp:
  endpoint: /dvdtheque-ws-service
  relay:
    host: 192.168.1.105
    port: 61613
    
hazelcast:
  cluster-name: hazelcast-local
  networkconfig:
    tcpipconfig:
      members: 192.168.1.133

keycloak:
  realm: dvdtheque
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: dvdtheque-api
  credentials:
    secret: 19a8c33e-89ec-4e5e-8e80-f752a896bf07
  use-resource-role-mappings: true
  cors: true
  bearer-only: true