debug: false
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    username: postgres
    password: zotla7
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dvdthequedb?currentSchema=dvdtheque-batch-service
  batch:
    initialize-schema: always
    initializer:
      enabled: false
    job:
      enabled: false
    stream:
      bindings:
        output:
          destination: input
      default:
        contentType: application/json
  activemq:
    broker-url: tcp://192.168.1.105:61616
    user: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/dvdtheque
          user-name-attribute: preferred_username
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/dvdtheque/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: dvdtheque-api
            client-secret: f81rhJxb18UyhOgvlmoswcBdG2RkhXqX
            authorization-grant-type: client_credentials

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

batch:
  export:
    cron: 0 20 11 * * ?
  save:
    nb:
      acteurs: 12

csv:
  dvd:
    file:
      name:
        import: src/test/resources/ListeDVD.csv
rippedFlagTasklet:
  from:
    file: true
retrieve:
  date:
    insertion: false
excel:
  dvd:
    file:
      path:
        export: D:/dev/liste_dvd/
      name:
        export: export.xlsx

dvd:
  file:
    path: G:/films

dvdtheque-service:
  url: http://localhost:8762/dvdtheque-service
  films: /films/
  transformTmdbFilmToDvdThequeFilm: /transformTmdbFilmToDvdThequeFilm/tmdb
  cleanAllFilms: /films/cleanAllfilms
  buildDvd: /films/buildDvd
  saveFilm: /films/saveProcessedFilm
  
tmdb-service:
  url: http://localhost:8762/dvdtheque-tmdb-service
  byTitle: /retrieveTmdbFilmListByTitle/byTitle
  release-date: /retrieveTmdbFrReleaseDate/byTmdbId
  get-credits: /retrieveTmdbCredits/byTmdbId
  get-results: /retrieveTmdbFilm/byTmdbId
  
export.cron: 0 10 20 * * ?