debug: false
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    url: jdbc:mysql://192.168.1.100/dvdtheque?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: fredo
    password: fredo
  batch:
    initialize-schema: never
    initializer:
      enabled: false
    job:
      enabled: false
    stream:
      bindings:
        output:
          destination: input
      default:
        contentType: application/json
  activemq:
    broker-url: tcp://192.168.1.105:61616
    user: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://192.168.1.105:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://192.168.1.105:8080/auth/realms/dvdtheque
          user-name-attribute: preferred_username
      client:
        provider:
          keycloak:
            token-uri: http://192.168.1.105:8080/auth/realms/dvdtheque/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: dvdtheque-api
            client-secret: 19a8c33e-89ec-4e5e-8e80-f752a896bf07
            authorization-grant-type: client_credentials

eureka:
  instance:
    hostname: 192.168.1.103
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://192.168.1.103:8761/eureka/,http://192.168.1.105:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 2

batch:
  save:
    nb:
      acteurs: 12

csv:
  dvd:
    file:
      name:
        import: src/test/resources/ListeDVD.csv
rippedFlagTasklet:
  from:
    file: true
retrieve:
  date:
    insertion: false
excel:
  dvd:
    file:
      path:
        export:
      name:
        export: export.xlsx

dvd:
  file:
    path: G:/films

hazelcast:
  cluster-name: hazelcast-dev
  networkconfig:
    tcpipconfig:
      members: 192.168.1.105,192.168.1.103

dvdtheque-service:
  url: http://192.168.1.105:8762/dvdtheque-service
  films: /films/
  transformTmdbFilmToDvdThequeFilm: /transformTmdbFilmToDvdThequeFilm/tmdb
  cleanAllFilms: /films/cleanAllfilms
  buildDvd: /films/buildDvd
  saveFilm: /films/saveProcessedFilm
  
tmdb-service:
  url: http://192.168.1.105:8762/dvdtheque-tmdb-service
  byTitle: /retrieveTmdbFilmListByTitle/byTitle
  release-date: /retrieveTmdbFrReleaseDate/byTmdbId
  get-credits: /retrieveTmdbCredits/byTmdbId
  get-results: /retrieveTmdbFilm/byTmdbId