debug: false
spring:
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    url: jdbc:mysql://192.168.1.100/dvdtheque?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
    username: fredo
    password: fredo
  batch:
    initialize-schema: never
    initializer:
      enabled: false
    job:
      enabled: true
    stream:
      bindings:
        output:
          destination: input
      default:
        contentType: application/json
  rabbitmq:
    host: 192.168.99.100
    port: 32777
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/dvdtheque/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: dvdtheque-api
            client-secret: 19a8c33e-89ec-4e5e-8e80-f752a896bf07
            authorization-grant-type: client_credentials
            
#  main:
#    web-application-type: none

eureka:
  client:
    enabled: false

batch:
  save:
    nb:
      acteurs: 12

csv:
  dvd:
    file:
      name:
        import: src/test/resources/ListeDVD.csv
rippedFlagTasklet:
  from:
    file: true
retrieve:
  date:
    insertion: false
excel:
  dvd:
    file:
      path:
        export:
      name:
        export: export.xlsx

dvd:
  file:
    path: G:/films

hazelcast:
  cluster-name: hazelcast-local
  networkconfig:
    interface: 127.0.0.1

dvdtheque-service:
  url: http://localhost:8762/dvdtheque-service
  films: /films/
  transformTmdbFilmToDvdThequeFilm: /transformTmdbFilmToDvdThequeFilm/tmdb
  
tmdb-service:
  url: http://localhost:8762/dvdtheque-tmdb-service
  byTitle: /retrieveTmdbFilmListByTitle/byTitle
  release-date: /retrieveTmdbFrReleaseDate/byTmdbId
  get-credits: /retrieveTmdbCredits/byTmdbId
  get-results: /retrieveTmdbFilm/byTmdbId