server:
  port: 8087

spring:
  datasource:
    username: dvdtheque
    password: zotla7
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.1.108:5432/dvdthequedb?currentSchema=dvdtheque-allocine-service
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://192.168.1.105:8080/auth/realms/dvdtheque-dev
          user-name-attribute: preferred_username
      client:
        provider:
          keycloak:
            token-uri: http://192.168.1.105:8080/auth/realms/dvdtheque-dev/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: dvdtheque-api
            client-secret: xJCl7Y8cvnAqaPIkXJRJeEvdo9GHb0Pz
            authorization-grant-type: client_credentials

eureka:
  instance:
    hostname: 192.168.1.103
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://192.168.1.103:8761/eureka/,http://192.168.1.105:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 2
 
fichefilm:
  parsing:
    page: 200
    cron: 0 15 19 * * ?