server:
  port: 8086

spring:
  security:
    client:
      registration:
        keycloak:
          provider: dvdtheque-realm
          client-id: gateway-client
          client-secret: 86efef59-d234-4a72-9de0-24ee2461effd
          authorization-grant-type: client_credentials
          token-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/token
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/dvdtheque-realm
          user-name-attribute: preferred_username

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
themoviedb:
  search:
    movie:
      query: https://api.themoviedb.org/3/search/movie
  movie:
    query: https://api.themoviedb.org/3/movie/
  api:
    key: aa87a44fb22d65986512188cd2ec2ca0
  poster:
    path:
      url: http://image.tmdb.org/t/p/w500
  
hazelcast:
  cluster-name: hazelcast-tmdb-local
  networkconfig:
    tcpipconfig:
      members: 127.0.0.1
      
logging:
  level:
    org:
        springframework:
          security:
            web: TRACE