server:
  port: 8083

logging:
  level:
    root: INFO
  file:
    path: /opt/dvdtheque_rest_service/logs/dvdtheque-service.log

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://192.168.1.105:8080/auth/realms/dvdtheque
          user-name-attribute: preferred_username
  datasource:
    username: dvdtheque
    password: zotla7
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.1.108:5432/dvdthequepdb?currentSchema=dvdtheque-service
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: false
  batch:
    job:
      enabled: false
  activemq:
    broker-url: tcp://192.168.1.108:61616
    user: admin
    password: admin
  zipkin:
    enabled: false
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

hibernate:
  hbm2ddl:
    auto: validate

batch:
  save:
    nb:
      acteurs: 18
limit:
  film:
    size: 40

tmdb-service:
  url: http://192.168.1.106:8762/dvdtheque-tmdb-service
  byTitle: /retrieveTmdbFilmListByTitle/byTitle
  byTitle-byPage: /retrieveTmdbSearchResultsByTitle/byTitle
  release-date: /retrieveTmdbFrReleaseDate/byTmdbId
  get-credits: /retrieveTmdbCredits/byTmdbId
  get-results: /retrieveTmdbFilm/byTmdbId

dvdtheque-batch-service:
  url: http://192.168.1.106:8762/dvdtheque-batch-service
  import: /invokejob/importFilmsJob

allocine-service:
  url: http://192.168.1.106:8762/dvdtheque-allocine-service
  byTitle: /byTitle
  byId: /byId
themoviedb:
  poster:
    path:
      url: http://image.tmdb.org/t/p/w500

eureka:
  instance:
    hostname: 192.168.1.106
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://192.168.1.106:8761/eureka/,http://192.168.1.108:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 2

stomp:
  endpoint: /dvdtheque-ws
  relay:
    host: 192.168.1.108
    port: 61613
    
hazelcast:
  cluster-name: hazelcast-prod
  networkconfig:
    tcpipconfig:
      members: 192.168.1.106,192.168.1.108
