server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8080/auth/realms/dvdtheque-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/dvdtheque
          user-name-attribute: preferred_username

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
themoviedb:
  search:
    movie:
      query: https://api.themoviedb.org/3/search/movie
  movie:
    query: https://api.themoviedb.org/3/movie/
  api:
    key: aa87a44fb22d65986512188cd2ec2ca0
  poster:
    path:
      url: http://image.tmdb.org/t/p/w500
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    enabled: true